export {
  LOOPBACK_AMS_NET_ID,
  DEFAULT_IO_ADS_PORT,
  DEFAULT_MAX_WAIT_UNTIL_MS,
  DEFAULT_NC_ADS_PORT,
  extensionConfigSchema,
  isWriteAllowed,
  normalizeExtensionConfig,
  type AdsConnectionMode,
  type AdsDirectConnectionConfig,
  type AdsNamedServiceConfig,
  type AdsRouterConnectionConfig,
  type ExtensionConfigInput,
  type ExtensionRuntimeConfig,
  type PlcAdsNamedServiceConfig,
  type TwinCatAdsServiceConfigs,
  type TwinCatAdsServiceName,
  type WritePolicy,
} from "twincat-mcp-core";
